name: moovi_time
description: A movie app made with Flutter.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter
  # Internationalization and localization facilities, including message translation,
  # plurals and genders, date/number formatting and parsing, and bidirectional text
  intl: any
  # Immutable classes, copyWith, toString, json de/serialization
  freezed_annotation: ^2.2.0
  # State management Block
  flutter_bloc: ^8.1.2
  # Http client
  dio: ^5.0.1
  # Dependency injection
  get_it: ^7.2.0
  json_annotation: ^4.8.0
  # Dio client generator
  retrofit: ^4.0.1
  # Dio interceptor for pretty logging
  pretty_dio_logger: ^1.3.1
  # Checks internet connectivity (wifi, etc.)
  connectivity_plus: ^3.0.3
  # Show images from the internet and keep them in the cache directory
  cached_network_image: ^3.2.3
  # Svg Feather icons
  flutter_feather_icons: ^2.0.0
  # Generate random UUID strings
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint rules are inside `analysis_options.yaml` located in the root of the project
  flutter_lints: ^2.0.0
  # Dart file generator
  build_runner: ^2.3.3
  # Immutable classes, copyWith, toString, json de/serialization
  freezed: ^2.3.2
  # Used for serializing json
  json_serializable: ^6.6.1
  # User for retrofit client
  retrofit_generator: ^6.0.0
  # Create widgets that are platform aware
  flutter_platform_widgets: ^3.3.5

# The following section is specific to Flutter packages.
flutter:
  # Used for localizations
  # Build runner not working if generate: true
  # If I add a empty pubspec.yaml in the .dart_tool/flutter_gen directory it builds ok.
  # generate: true
  # Material icons and fonts
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
